services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=UnidadeDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"

  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db